[build]
  command   = "npm run build"
  functions = "out_functions"
  publish   = "out_publish"

[dev]
  functions = "out_functions"
  publish   = "out_publish"
  framework = "#static"

[[redirects]]
  from = "/merch"
  to = "https://merch.streamelements.com/bdougieyo"
  status = 200
  force = true