module.exports = {
  purge: [],
  theme: {
    colors: {
      accent: "#faeace",
      background: "#fffbf5",
      saucyred: "#d95c41",
      cheesyyellow: "#f6d809",
      offwhite: "#fbfbfb",
      lightestgrey: "#e6e6e6",
      lightergrey: "#bcbcbc",
      lightgrey: "#8b8b8b",
      backgroundgrey: "#2F372E",
      grey: "#313d3e",
      darkgrey: "#171c1d",
      darkestgrey: "#0c0e0e",
      gold: "#f6bc00",
      orange: "#fe9d68",
      blue: "#4d9abf",
      green: "#00c7b7",
      darkgreen: "#03b1a3",
      red: "#fb6d77",
      darkred: "#fa3946",
    },
    extend: {},
  },
  variants: {},
  plugins: [],
};
